# The following iterative sequence is defined for the set of positive integers:

# n → n/2 (n is even)

# n → 3n + 1 (n is odd)

# Using the rule above and starting with 13, we generate the following sequence:

# 13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

# It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

# Which starting number, under the given limit, produces the longest chain?

# Note: Once the chain starts the terms are allowed to go above one million.


def Collatz(n):
	# returns the longest Collatz sequence generated by a number less than n

	larseq = []
	for i in range(2, n):
		sequence=[]
		while i!=1:
			sequence.append(int(i))
			if not i%2:
				i=i/2
				continue
			else:
				i = 3*i + 1
				continue
		sequence.append(1)
		if len(larseq)<len(sequence):
			larseq = sequence
		else:
			pass
	return larseq


print(Collatz(100))	
