# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

def fibsum(num):
	lis = [1,2]
	liseven = []
	if num==1:
		return 0
	while lis[-1]<num and lis[-1]+lis[-2]<=num:
		j = lis[-1]+lis[-2]
		lis.append(j)
		# this loop generates the fibonacci series

	for i in lis:
		if not i%2:
			liseven.append(i)
	# print(lis)
	# print(liseven)
	return sum(liseven)

print(fibsum(100000))
